from datetime import date

DRIVERS_2025 = [
    {
        "name": "Max Verstappen",
        "team": "Red Bull Racing",
        "country": "Pays-Bas",
        "flag": "🇳🇱",
        "number": 1,
        "image": "",
        "base_odds": 2.10,
    },
    {
        "name": "Sergio Pérez",
        "team": "Red Bull Racing",
        "country": "Mexique",
        "flag": "🇲🇽",
        "number": 11,
        "image": "",
        "base_odds": 4.80,
    },
    {
        "name": "Charles Leclerc",
        "team": "Ferrari",
        "country": "Monaco",
        "flag": "🇲🇨",
        "number": 16,
        "image": "",
        "base_odds": 4.00,
    },
    {
        "name": "Carlos Sainz",
        "team": "Williams",
        "country": "Espagne",
        "flag": "🇪🇸",
        "number": 55,
        "image": "",
        "base_odds": 12.00,
    },
    {
        "name": "Lewis Hamilton",
        "team": "Ferrari",
        "country": "Royaume-Uni",
        "flag": "🇬🇧",
        "number": 44,
        "image": "",
        "base_odds": 5.50,
    },
    {
        "name": "George Russell",
        "team": "Mercedes",
        "country": "Royaume-Uni",
        "flag": "🇬🇧",
        "number": 63,
        "image": "",
        "base_odds": 8.50,
    },
    {
        "name": "Lando Norris",
        "team": "McLaren",
        "country": "Royaume-Uni",
        "flag": "🇬🇧",
        "number": 4,
        "image": "",
        "base_odds": 6.00,
    },
    {
        "name": "Oscar Piastri",
        "team": "McLaren",
        "country": "Australie",
        "flag": "🇦🇺",
        "number": 81,
        "image": "",
        "base_odds": 7.50,
    },
    {
        "name": "Fernando Alonso",
        "team": "Aston Martin",
        "country": "Espagne",
        "flag": "🇪🇸",
        "number": 14,
        "image": "",
        "base_odds": 15.00,
    },
    {
        "name": "Lance Stroll",
        "team": "Aston Martin",
        "country": "Canada",
        "flag": "🇨🇦",
        "number": 18,
        "image": "",
        "base_odds": 60.00,
    },
    {
        "name": "Pierre Gasly",
        "team": "Alpine",
        "country": "France",
        "flag": "🇫🇷",
        "number": 10,
        "image": "",
        "base_odds": 45.00,
    },
    {
        "name": "Esteban Ocon",
        "team": "Alpine",
        "country": "France",
        "flag": "🇫🇷",
        "number": 31,
        "image": "",
        "base_odds": 50.00,
    },
    {
        "name": "Valtteri Bottas",
        "team": "Sauber",
        "country": "Finlande",
        "flag": "🇫🇮",
        "number": 77,
        "image": "",
        "base_odds": 80.00,
    },
    {
        "name": "Zhou Guanyu",
        "team": "Sauber",
        "country": "Chine",
        "flag": "🇨🇳",
        "number": 24,
        "image": "",
        "base_odds": 90.00,
    },
    {
        "name": "Yuki Tsunoda",
        "team": "RB",
        "country": "Japon",
        "flag": "🇯🇵",
        "number": 22,
        "image": "",
        "base_odds": 70.00,
    },
    {
        "name": "Daniel Ricciardo",
        "team": "RB",
        "country": "Australie",
        "flag": "🇦🇺",
        "number": 3,
        "image": "",
        "base_odds": 65.00,
    },
    {
        "name": "Alexander Albon",
        "team": "Williams",
        "country": "Thaïlande",
        "flag": "🇹🇭",
        "number": 23,
        "image": "",
        "base_odds": 55.00,
    },
    {
        "name": "Logan Sargeant",
        "team": "Williams",
        "country": "États-Unis",
        "flag": "🇺🇸",
        "number": 2,
        "image": "",
        "base_odds": 120.00,
    },
    {
        "name": "Nico Hülkenberg",
        "team": "Haas",
        "country": "Allemagne",
        "flag": "🇩🇪",
        "number": 27,
        "image": "",
        "base_odds": 85.00,
    },
    {
        "name": "Kevin Magnussen",
        "team": "Haas",
        "country": "Danemark",
        "flag": "🇩🇰",
        "number": 20,
        "image": "",
        "base_odds": 95.00,
    },
]


RACES_2025 = [
    {
        "name": "Grand Prix de Bahreïn",
        "circuit": "Sakhir",
        "city": "Sakhir",
        "country": "Bahreïn",
        "flag": "🇧🇭",
        "date": date(2026, 3, 14),
        "laps": 57,
        "distance": 308.0,
        "image": "https://sports-cars.fr/wp-content/uploads/2025/04/Grand-Prix-de-Bahrein.jpg",
    },
    {
        "name": "Grand Prix d'Arabie Saoudite",
        "circuit": "Jeddah Corniche",
        "city": "Djeddah",
        "country": "Arabie Saoudite",
        "flag": "🇸🇦",
        "date": date(2026, 3, 21),
        "laps": 50,
        "distance": 308.4,
        "image": "https://franceracing.fr/wp-content/uploads/2022/11/Le-circuit-Arabie-saoudite-F1.jpg",
    },
    {
        "name": "Grand Prix d'Australie",
        "circuit": "Albert Park",
        "city": "Melbourne",
        "country": "Australie",
        "flag": "🇦🇺",
        "date": date(2026, 4, 6),
        "laps": 58,
        "distance": 307.6,
        "image": "https://img.20mn.fr/Vpa1K7hyRyS_CxEG6blV9Sk/1444x920_il-faudra-veiller-pour-suivre-le-grand-prix-d-australie-en-direct-ce-week-end",
    },
    {
        "name": "Grand Prix du Japon",
        "circuit": "Suzuka",
        "city": "Suzuka",
        "country": "Japon",
        "flag": "🇯🇵",
        "date": date(2026, 4, 13),
        "laps": 53,
        "distance": 307.5,
        "image": "https://sportscar365.com/wp-content/uploads/2019/08/SuzukaCircuit.jpg",
    },
    {
        "name": "Grand Prix de Chine",
        "circuit": "Shanghai International",
        "city": "Shanghai",
        "country": "Chine",
        "flag": "🇨🇳",
        "date": date(2026, 4, 20),
        "laps": 56,
        "distance": 305.2,
        "image": "https://sf1.sportauto.fr/wp-content/uploads/sportauto/2022/11/xpb_1135502_1200px-750x410.jpg",
    },
    {
        "name": "Grand Prix de Miami",
        "circuit": "Miami International Autodrome",
        "city": "Miami",
        "country": "États-Unis",
        "flag": "🇺🇸",
        "date": date(2026, 5, 4),
        "laps": 57,
        "distance": 308.3,
        "image": "https://offloadmedia.feverup.com/secretmiami.com/wp-content/uploads/2023/04/13053919/shutterstock_2153075875-2.jpg",
    },
    {
        "name": "Grand Prix d'Émilie-Romagne",
        "circuit": "Imola",
        "city": "Imola",
        "country": "Italie",
        "flag": "🇮🇹",
        "date": date(2026, 5, 18),
        "laps": 63,
        "distance": 309.0,
        "image":"https://franceracing.fr/wp-content/uploads/2020/07/Imola-1.jpg",
    },
    {
        "name": "Grand Prix de Monaco",
        "circuit": "Monte-Carlo",
        "city": "Monte-Carlo",
        "country": "Monaco",
        "flag": "🇲🇨",
        "date": date(2026, 5, 25),
        "laps": 78,
        "distance": 260.3,
        "image": "https://imgresizer.eurosport.com/unsafe/1200x0/filters:format(jpeg)/origin-imgresizer.eurosport.com/2019/05/26/2597706-53852830-2560-1440.jpg",
    },
    {
        "name": "Grand Prix du Canada",
        "circuit": "Gilles Villeneuve",
        "city": "Montréal",
        "country": "Canada",
        "flag": "🇨🇦",
        "date": date(2026, 6, 8),
        "laps": 70,
        "distance": 305.3,
        "image": "https://f1i.autojournal.fr/wp-content/uploads/sites/17/2018/06/DfFqAgYXcAAbfwU.jpg",
    },
    {
        "name": "Grand Prix d'Espagne",
        "circuit": "Barcelone-Catalogne",
        "city": "Barcelone",
        "country": "Espagne",
        "flag": "🇪🇸",
        "date": date(2026, 6, 22),
        "laps": 66,
        "distance": 307.2,
        "image": "https://www.f1-fansite.com/wp-content/uploads/2021/04/Spanish-F1-Grand-Prix-layout.jpg",
    },
    {
        "name": "Grand Prix d'Autriche",
        "circuit": "Red Bull Ring",
        "city": "Spielberg",
        "country": "Autriche",
        "flag": "🇦🇹",
        "date": date(2026, 6, 29),
        "laps": 71,
        "distance": 306.5,
        "image": "https://amp.nextgen-auto.com/IMG/logo/arton149449.jpg",
    },
    {
        "name": "Grand Prix de Grande-Bretagne",
        "circuit": "Silverstone",
        "city": "Silverstone",
        "country": "Royaume-Uni",
        "flag": "🇬🇧",
        "date": date(2026, 7, 6),
        "laps": 52,
        "distance": 306.2,
        "image": "https://amp.nextgen-auto.com/IMG/logo/arton139432.jpg",
    },
    {
        "name": "Grand Prix de Hongrie",
        "circuit": "Hungaroring",
        "city": "Budapest",
        "country": "Hongrie",
        "flag": "🇭🇺",
        "date": date(2026, 7, 20),
        "laps": 70,
        "distance": 306.6,
        "image": "https://franceracing.fr/wp-content/uploads/2023/07/2023-Hungaorring.jpg",
    },
    {
        "name": "Grand Prix de Belgique",
        "circuit": "Spa-Francorchamps",
        "city": "Spa",
        "country": "Belgique",
        "flag": "🇧🇪",
        "date": date(2026, 8, 3),
        "laps": 44,
        "distance": 308.1,
        "image": "https://i.redd.it/aerial-view-of-the-preparations-at-spa-francorchamps-for-v0-s1qwbcm4eodf1.jpg?width=3000&format=pjpg&auto=webp&s=b84a4a730d4beb6dd7e780e950108855c2ebd92d",
    },
    {
        "name": "Grand Prix des Pays-Bas",
        "circuit": "Zandvoort",
        "city": "Zandvoort",
        "country": "Pays-Bas",
        "flag": "🇳🇱",
        "date": date(2026, 8, 31),
        "laps": 72,
        "distance": 306.6,
        "image": "https://franceracing.fr/wp-content/uploads/2019/05/Dutch-Grand-Prix-2-bis-Copier.jpg",
    },
    {
        "name": "Grand Prix d'Italie",
        "circuit": "Monza",
        "city": "Monza",
        "country": "Italie",
        "flag": "🇮🇹",
        "date": date(2026, 9, 7),
        "laps": 53,
        "distance": 306.7,
        "image": "https://i0.wp.com/f1nal-lap.be/wp-content/uploads/2019/09/Couverture.jpg?resize=1140%2C744&ssl=1",
    },
    {
        "name": "Grand Prix d'Azerbaïdjan",
        "circuit": "Bakou",
        "city": "Bakou",
        "country": "Azerbaïdjan",
        "flag": "🇦🇿",
        "date": date(2026, 9, 21),
        "laps": 51,
        "distance": 306.1,
        "image": "https://media.ouest-france.fr/v1/pictures/MjAyMTA2N2EyZmE5NzYyNjQ5YjlmNGUxYmRjZDY3NzJhN2JkZjI?width=1260&height=708&focuspoint=50%2C50&cropresize=1&client_id=bpeditorial&sign=dc591d44a2644c9aa1e7df68faa9e7a306423989c8b9bef6d044b62a8bb06161",
    },
    {
        "name": "Grand Prix de Singapour",
        "circuit": "Marina Bay",
        "city": "Singapour",
        "country": "Singapour",
        "flag": "🇸🇬",
        "date": date(2026, 10, 4),
        "laps": 61,
        "distance": 308.7,
        "image": "https://static.tickets-platform.com/img/pages/81/2121/10356/feature/feature_image.jpg",
    },
    {
        "name": "Grand Prix des États-Unis (Austin)",
        "circuit": "Circuit of the Americas",
        "city": "Austin",
        "country": "États-Unis",
        "flag": "🇺🇸",
        "date": date(2026, 10, 18),
        "laps": 56,
        "distance": 308.4,
        "image": "https://www.formulatours.com/wp-content/uploads/2020/02/PISTE-USA-2.jpg",
    },
    {
        "name": "Grand Prix du Mexique",
        "circuit": "Autodromo Hermanos Rodriguez",
        "city": "Mexico",
        "country": "Mexique",
        "flag": "🇲🇽",
        "date": date(2026, 10, 25),
        "laps": 71,
        "distance": 305.3,
        "image": "https://static.wui.fr/28/2022/10/photo_article/1138/641/1200-L-f1-gp-mexique-2022-circuit-chronos-guide-tv-des-essais-et-qualifications.jpg",
    },
    {
        "name": "Grand Prix du Brésil",
        "circuit": "Interlagos",
        "city": "São Paulo",
        "country": "Brésil",
        "flag": "🇧🇷",
        "date": date(2026, 11, 8),
        "laps": 71,
        "distance": 305.9,
        "image": "https://f1i.autojournal.fr/wp-content/uploads/sites/17/2018/11/interlagos-f1-1.jpg",
    },
    {
        "name": "Grand Prix de Las Vegas",
        "circuit": "Las Vegas Strip Circuit",
        "city": "Las Vegas",
        "country": "États-Unis",
        "flag": "🇺🇸",
        "date": date(2026, 11, 21),
        "laps": 50,
        "distance": 305.0,
        "image": "https://franceracing.fr/wp-content/uploads/2023/03/Las-Vegas-Grand-Prix-F1-4.jpg",
    },
    {
        "name": "Grand Prix du Qatar",
        "circuit": "Losail",
        "city": "Lusail",
        "country": "Qatar",
        "flag": "🇶🇦",
        "date": date(2026, 11, 28),
        "laps": 57,
        "distance": 308.6,
        "image": "https://sf1.sportauto.fr/wp-content/uploads/sportauto/2021/11/image.jpeg",
    },
    {
        "name": "Grand Prix d'Abou Dabi",
        "circuit": "Yas Marina",
        "city": "Abou Dabi",
        "country": "Émirats arabes unis",
        "flag": "🇦🇪",
        "date": date(2026, 12, 6),
        "laps": 58,
        "distance": 306.1,
        "image": "https://franceracing.fr/wp-content/uploads/2020/12/Yas-Marina-Circuit.jpg",
    },
]

