from django.urls import path

from .views import (
    AdminBetsView,
    AdminDriversView,
    AdminDriverDetailView,
    AdminImportAssociationsView,
    AdminImportCleanView,
    AdminImportDriversView,
    AdminImportRacesView,
    AdminRaceDetailView,
    AdminRaceDriverView,
    AdminRacesView,
    AdminSettleBetView,
    AdminStatsView,
    AdminUserBanView,
    AdminUserRoleView,
    AdminUsersView,
    DriverListView,
    LeaderboardView,
    LoginView,
    MeView,
    MyBetsView,
    PlaceBetView,
    RaceDetailView,
    RaceDriversView,
    RaceListView,
    SignupView,
    UserStatsView,
)

urlpatterns = [
    path('auth/signup', SignupView.as_view()),
    path('auth/login', LoginView.as_view()),
    path('auth/me', MeView.as_view()),
    path('races', RaceListView.as_view()),
    path('races/<int:race_id>', RaceDetailView.as_view()),
    path('races/<int:race_id>/drivers', RaceDriversView.as_view()),
    path('drivers', DriverListView.as_view()),
    path('bets/place', PlaceBetView.as_view()),
    path('bets/my-bets', MyBetsView.as_view()),
    path('leaderboard', LeaderboardView.as_view()),
    path('stats/user/<int:user_id>', UserStatsView.as_view()),
    # Admin
    path('admin/stats', AdminStatsView.as_view()),
    path('admin/users', AdminUsersView.as_view()),
    path('admin/users/<int:user_id>/ban', AdminUserBanView.as_view()),
    path('admin/users/<int:user_id>/role', AdminUserRoleView.as_view()),
    path('admin/races', AdminRacesView.as_view()),
    path('admin/races/<int:race_id>', AdminRaceDetailView.as_view()),
    path('admin/drivers', AdminDriversView.as_view()),
    path('admin/drivers/<int:driver_id>', AdminDriverDetailView.as_view()),
    path('admin/races/<int:race_id>/drivers', AdminRaceDriverView.as_view()),
    path('admin/races/<int:race_id>/drivers/<int:driver_id>', AdminRaceDriverView.as_view()),
    path('admin/bets', AdminBetsView.as_view()),
    path('admin/bets/<uuid:bet_id>/settle', AdminSettleBetView.as_view()),
    path('admin/import/clean', AdminImportCleanView.as_view()),
    path('admin/import/drivers', AdminImportDriversView.as_view()),
    path('admin/import/races', AdminImportRacesView.as_view()),
    path('admin/import/associations', AdminImportAssociationsView.as_view()),
]

